version: "3"
services:
  tryon-app:
    container_name: tryon-container
    image: ziadgad/tryon-docker
    ports:
      - "3000:3000"
    env_file:
      - ./config.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/*.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 161123
      MONGO_INITDB_DATABASE: tryon

  redis:
    image: redis

  caddy:
    image: caddy:latest
    container_name: caddy-container
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - tryon-app
      
volumes:
  mongo-db:
  caddy_data:
  caddy_config:
  